### ISSUE TITLE
Default implementation for fromValue?

### ISSUE THREAD

**Issue by ncfavier** [glguy/toml-parser#14]
Analogously to what aeson does with [`FromJSON`](https://hackage.haskell.org/package/aeson-2.2.0.0/docs/Data-Aeson.html#v:parseJSON), it would be nice to have a default implementation of `fromValue` for `Generic` types:

```hs
    default fromValue :: Generic a => Value -> Matcher a
    fromValue = parseTableFromValue genericParseTable
```

This introduces a cyclic dependency between `Toml.FromValue` and `Toml.FromValue.Generic` though.

**Comment by glguy** [comment]
I intentionally didn't write out the default like this because I find this kind of defaulting to be unnecessarily magical, in general. I like being able to see what the actual definition is, click "Go To Declaration" with HLS, etc.

That said I'm willing to be convinced it makes life a lot better for others. Even if it's implemented I wouldn't have to use it, myself.

**Comment by glguy** [comment]
With the new `Toml.Generic` module you can do:

```haskell
data Config = Config
  { server :: Text
  , tls :: Bool
  , port :: Int
  , nick :: Text
  , password :: Maybe Text
  , realName :: Text
  , channels :: [Text]
  , commandPrefix :: Text
  , urlAlternativeHosts :: Map Text Text
  , merriamWebsterKey :: Maybe Text
  , wolframAlphaKey :: Maybe Text
  }
  deriving (Generic)
  deriving FromValue via GenericToml Config
```

and it'll be about the same amount of code but discoverable and readable.
