### ISSUE TITLE
Add 'aeson-like' interfaces for parsing

### ISSUE THREAD

**Issue by chshersh** [glguy/toml-parser#2]
Currently, if I want to store and parse my data type inside TOML file, I need to manually pattern-match on the result of `parseTOML` function which can be awkward sometimes. Check this for example:

* https://github.com/ChShersh/life-sync/blob/665299c3992b5532ff494218a9bca4cfed62e659/src/Life/Configuration.hs#L135

What would be good is to have `aeson`-like interfaces, let's say `ToTOML` and `FromTOML` which allows to convert to TOML and from TOML representations. I'm not saying that `toml-parser` should completely mimic `aeson` design choices, maybe something better can be invented. But I think it's a useful addition to library.

What do you think?

**Comment by brandonchinn178** [comment]
I know this is an old issue, but just wanted to +1 this.

FWIW `tomland` is a pretty solid library, if one wants to support serialization + deserialization logic. However, I don't think serialization is something `toml-parser` needs to be concerned with, especially with the TOML v1.0.0 spec. The conceptual model for TOML is lossy: tables are syntax sugar for a bunch of `a.b.c.d = <primitive value>` lines, so it'd be difficult to know exactly what format you want to print things out as (e.g. should `a.b = 1` be printed out verbatim, or as `[a]\nb = 1`?). So I think instead of adding `ToTOML` (which this library doesn't provide primitives for anyway), you should just implement your own `prettyPrintMyType` to normalize the thing into the right TOML format.

But I do want to +1 a `FromTOML` type class, which shouldn't be difficult to add on top of what this library already provides.

**Comment by glguy** [comment]
toml-parser-1.0.0.0 has these classes and pretty-printing
